### ISSUE TITLE
Missing signalized intersection - Steeles between Woodbine and Victoria Park

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#775]
**What Happened**
MOVE shows one flush midblock where there is a signalized intersection (you can see traffic lights in the "aerial" image in MOVE) between Woodbine and Victoria Park, on Steeles.

**What Should Happen**
This segment should be displayed as two midblocks, and one intersection.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Steeles/Victoria Park (px: 1142)
2. Scroll to the midblock immediately left/west

**Screenshots**
![Screenshot 2021-02-03 102240](https://user-images.githubusercontent.com/3179624/106768311-cc1b1d80-6609-11eb-9824-7e53c6cedbed.png)

**Additional Notes**
n/a

**Comment by mkewins** [comment]
Shawn Dillon reported another missing intersection at Lansdowne / Lansdowne.

The intersection is located south of `Lansdowne Ave / Dundas St W` and north of `Lansdowne Ave / Shirley St`.

![Shawn Dillon - Missing Intersection](https://user-images.githubusercontent.com/3179624/106818663-98aab400-6646-11eb-8bdf-001bef7ce7c4.png)

**Comment by candu** [comment]
Looking deeper into this: in both cases, the issue is that the intersection isn't in the centreline, so fixing this would mean either a) maintaining our own patch to the centreline or b) getting it fixed upstream somehow.

For the Steeles and Victoria Park case: the road south off of Steeles looks to be a private entrance to some sort of technology / office park - private driveways, roads, etc. aren't in the centreline; only City-maintained roads are.

For the Lansdowne / Lansdowne intersection: not sure why this isn't in the centreline, but it's not; maybe the intersection just north of the circled area is intended to capture this leg as well?

I'm not sure what our approach _should_ be here - in general, it's unlikely we'll _ever_ achieve 100% accuracy, no matter what data we use for the road network, and using the Centreline as-is gives us a lot of value.  This feels like a thing where we may just have to communicate this to our users.
