### ISSUE TITLE
Hide non-matching sub-requests in Track Requests for filter / search / sort and download

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#881]
**Description**
From QA testing for v1.3 (thanks @mkewins !):

> one weird thing:
>
> 1. apply a study type filter (speed / vol ATR)
> 2. download all
> 3. open downloaded file
>
> there are other types of studies in the download, not just speed / vol ATR requests (TMCs, ped delays, etc.)

This is due to how we implement filter / search / sort:

> right now, if anything in a bulk request matches, it fetches and shows the entire bulk request (including any study requests that don't match).

This task aims to clean that up, and only show matching study requests within the bulk request.

**Acceptance Criteria**
- [ ] when applying filter / search / sort, only matching study requests within bulk requests are shown;
- [ ] when downloading all, only matching study requests within bulk requests are included.

**Additional Notes**
Together with #880 , this points to the need to be able to apply filter / search / sort at the individual study request level.

**Comment by mkewins** [comment]
A related piece of feedback – @candu let me know if this should be filed as a separate issue – the totals on the Track Requests page are confusing / misleading because we only count 25 objects, regardless of whether these are single or bulk requests. [A further write-up is here (internal link only).](https://www.notion.so/bditto/Track-Requests-table-totals-are-off-with-bulk-requests-26fcab7cbcb24986a605c3ae85616066)

Example:

- 25 items on page
- 24 are single requests
- 1 is a project / bulk request with 13 requests in it
- Therefore, there are actually 24 + 13 = 37 requests on the page, not 25

**Comment by mkewins** [comment]
Does the changes for Release 1.8 solve this? Tagging as `dev-review-needed`.
