### ISSUE TITLE
Martin Grove / Eglinton Ave W does not show up in search results

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#964]
**What Happened**
The intersection of [Martin Grove Road / Eglinton Ave W](https://move.intra.prod-toronto.ca/view/location/s1:ACztmB/POINTS) does not show up in the list of search results.

**What Should Happen**
This intersection should show up since it's a major intersection.

**To Reproduce**
Steps to reproduce the bug:
1. Click on the search bar
2. Type in "Martin Grove / Eglinton"
3. Scan search result suggestions, see that the intersection (named "[Martin Grove Rd / Eglinton Ave W](https://move.intra.prod-toronto.ca/view/location/s1:ACztmB/POINTS)") does not appear in search results

**Screenshots**
![Screenshot 2021-06-11 113349](https://user-images.githubusercontent.com/3179624/121711737-eb8af100-caa8-11eb-8534-71ce86719bc7.png)

**Additional Notes**
On the View Data page, the intersection is classified as a "Cul-de-sac Intersection".

I tried doing _a bit_ of digging to see if the fact that the intersection is classified as a cul-de-sac was playing a factor. Didn't get too far, but there are _two_ entries for centreline id `13463137`. One is a `Major Intersection` and one is a `Cul de sac`.
```sql
select * from gis.centreline_intersection where int_id = 13463137;
807579	13463137	38414	"Martin Grove Rd / Eglinton Ave W"	"MJRML"	"Major-Multi Level"	2	509100	"Cul de sac"	9	0		0		299689.935	4836950.134	-79.563176723	43.674477761	4258	"0101000020E6100000D2C961160BE453C0E9AF8A4955D64540"
807580	13463137	32894	"Martin Grove Rd / Eglinton Ave W"	"MJRML"	"Major-Multi Level"	2	501200	"Major"	0	0		0		299689.935	4836950.134	-79.563176723	43.674477761	4259	"0101000020E6100000D2C961160BE453C0E9AF8A4955D64540"
```

**Comment by candu** [comment]
@mkewins - thanks for doing even that bit of digging!

Indeed, there can be more than one row for the same `int_id` in `gis.centreline_intersection`.  To deal with this, we normalize using `SELECT DISTINCT ON (int_id)` early in the centreline conflation pipeline:

```sql
INSERT INTO centreline.intersections_base (
  SELECT DISTINCT ON (gci.int_id)
    -- a bunch of columns...
  FROM gis.centreline_intersection gci
  -- ...and no ORDER BY clause!
);
```

The lack of `ORDER BY` appears to be the issue here.  From [PostgreSQL `DISTINCT` docs](https://www.postgresql.org/docs/9.6/sql-select.html#SQL-DISTINCT):

> SELECT DISTINCT ON ( expression [, ...] ) keeps only the first row of each set of rows where the given expressions evaluate to equal. The DISTINCT ON expressions are interpreted using the same rules as for ORDER BY (see above). **Note that the "first row" of each set is unpredictable unless ORDER BY is used to ensure that the desired row appears first.**

(emphasis mine)

This could easily lead to a case where one environment picks the major intersection record, while another picks the cul-de-sac...and this is indeed what we see; when I wrote this up, dev picked the former, while QA / prod both picked the latter.

Duplicate `int_id` values are actually not that uncommon, so we should probably do at least a bit of further planning before committing to `ORDER BY` as a fix:

```sql
flashcrow=> select count(*) from gis.centreline_intersection;
 count 
-------
 53735
(1 row)

flashcrow=> select count(distinct(int_id)) from gis.centreline_intersection;
 count 
-------
 46073
(1 row)
```

**Comment by candu** [comment]
Martin Grove / Eglinton is now available in QA search results - marking closed.
