### ISSUE TITLE
Not showing all 3 zones in Ped Delay Reports page

### ISSUE THREAD

**Issue by shinechaudhuri** [CityofToronto/bdit_flashcrow#996]
**What Happened**
In the Ped Delay Reports page, Ossington Ave / Geary Ave shows only Zone A on MOVE, there is a Zone B and Zone C that is not shown

**What Should Happen**
Show Zone B and Zone C along with Zone A in the reports page.

**Comment by mkewins** [comment]
This occurred at Geary / Ossington.

**Comment by mkewins** [comment]
Quick notes from discussion:
- If this is a one-off case; great!
- We need more fundamental tools / processes for edit / delete data in the long run.

**Comment by candu** [comment]
This looks like a parsing issue: maybe the zone table landmarks are different / missing somehow?

Another possible parsing issue in Campbell Ave / Antler St?  This might be an issue with column ordering, but need to investigate further.

**Comment by candu** [comment]
Looking first at Geary / Ossington (ID: `PED_DELAY/153`).

This comes from source file `/data/ped_delays/OLD/PED_DELAYS/2020/excel/97674_GEARY AVE and OSSINGTON AVE_Zone C.json` - the problem here is that, in the network drive, ped delays with more than 2 zones often show up as multiple files:

1. one file covering zones A, B;
2. one file covering zone C;
3. one file that combines A, B, C.

This source file corresponds to 2) above; what we'd _ideally_ want is just 3), not 1) or 2).

Indeed, if you use the date dropdown at this location, you'll see 1), 2), and 3) above, each listed as a separate delay.

One way to fix this would be to special-case the parser to notice if there are files with the same ATS ID.  This has several drawbacks:

- it wouldn't work for counts that don't have the ATS ID in the filename;
- it introduces a cross-file dependency, whereas the parser as currently written doesn't have to depend on that;
- it encodes a quirk of how these are stored into the process, where what we _really_ want is to eliminate the quirk.

IMHO the better path here would be to keep this in mind as a manual cleanup task here: we should not store 1), 2), 3) above in the same folder on the network drive, only 3).

**Comment by candu** [comment]
Now on to Campbell / Antler 2017 (ID: `PED_DELAY/494`).

This comes from source file `/data/ped_delays/OLD/PED_DELAYS/2017/excel/82840_Antler&Campbell_PedDelay_Routine.json`, which shows no errors detected by the parser.  (This is not to say that there are no errors; only that, if there are, they're of a kind we don't currently detect.)

The totals and number of crossings match in this data file.  Maybe the parser has somehow identified both Total Pedestrians and Number of Crossings as appearing in the same column?

Looking through `parse_ped_delay.py`, this _could_ happen if the parser can't find the "Total Pedestrians" landmark.  In that case, it would read across the first 11 columns after "Time", taking the first 10 as ped types by delayed vs. not-delayed breakdown, and the the 11th as crossings.

That does indeed seem to be the problem.  Looking at the Excel sheet shows why:
![Antler and Campbell summary sheet](https://user-images.githubusercontent.com/151605/123845799-9fcaab00-d8e2-11eb-89d1-e31d88d3f32d.png)

In most Ped Delay Excel files, the "Total of Pedestrians" cell starts on the same row as the top-left zone marker ("Zone A", in this case).  That's not true here - so it doesn't find a value for `c_total`, and takes the total column as crossings instead.

**Comment by candu** [comment]
Continuing our look at Campbell / Antler 2017 - there's another issue where the two Youth and Adults columns are swapped.  What's going on there?

From the screenshot above, we see that the ordering of the columns in each pedestrian type is "=<10sec", ">10sec" - that is, non-delayed, then delayed.  Checking a few other files, this appears to be a common ordering.

From `parse_ped_delays.py`, we see that the order in `DATA_PARAMS` is `ac_d`, `ac_nd` (and similar for other types) - that is, delayed, then non-delayed.

So if this is more generally an issue, we'd expect to see swapped columns in _every_ ped delay report.  Let's look at a few:

- Trethewey and Paulson 2020: columns are swapped for all types;
- Greer and Lawrence 2018: columns are swapped for all types;
- Kipling and Jutland 2015: columns are swapped for all types.

This is consistent with what we've found - I'll swap the order of these in `DATA_PARAMS`, which should fix this particular issue.

Looping back to the crossings issue: one thought we had before was to search not just the "Zone A" row, but also every row between "Zone A" (inclusive) and "Time" (exclusive) for landmarks like "Total", "Number of".  This would catch cases like this, and shouldn't be _too_ hard to implement (definitely less time than specifying a precise layout and manually cleaning all this up).

**Comment by candu** [comment]
Checked again after parser fix: see [Campbell / Antler](https://move.intra.dev-toronto.ca/view/location/s1:AYhumB/POINTS/reports/PED_DELAY).  Crossings now look good, and delayed / non-delayed are no longer swapped.

Also quickly checked [Trethewey and Paulson](https://move.intra.dev-toronto.ca/view/location/s1:A-AsmB/POINTS/reports/PED_DELAY) from above - looks good as well.

PR coming shortly.

**Comment by candu** [comment]
@shinechaudhuri @mkewins I'm going to file a separate issue around manual cleanup, and then probably close this one.  This way, we can document / spec out manual cleanup tasks right here in GitHub, as part of handing those off to Data Collection as available time / effort permits.

**Comment by candu** [comment]
Linked #999 here, marking this as closed.
